In [57]:
import pandas as pd

In [58]:
dfa = pd.read_csv("../data/contacts.csv")

dfa = dfa[["RelationshipDescription", "Contact"]]

dfa = dfa.rename(columns={"RelationshipDescription": "title", "Contact": "officer_name"})

dfa = dfa[dfa.title.str.lower().str.strip().str.contains("police", "detective") ]

dfa = dfa[["officer_name"]]

dfa

            officer_name
9       Kenneth Mitchell
10         Clarence Gray
11         Eldridge Moll
12        Walter Chappel
13          David Lozano
...                  ...
7377  Chiquita Broussard
7393    Michael Cummings
7394    Michael Hullihan
7412       Donald Curole
7413           Ray Himel

[1728 rows x 1 columns]

In [59]:
dfb = pd.read_csv("../../preprocessing/data/output/clean.csv")

dfz = dfb.copy()

dfb = dfb[["officer_name"]]

,officer_context,officer_role,page_number,fn,query,prompt_template_for_hyde,prompt_template_for_model,chunk_size,chunk_overlap,temperature,...,iteration,num_of_queries,model,uid,officer_name,first_name,last_name,fc,lc,person_uid
2729,mentioned as the sergeant of the person being ...,sergeant,"[8, 52, 38, 29, 34, 39, 11, 49, 8, 48, 49, 8, ...",Exhibit 26 Herman Franklin Deposition Transcri...,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,1,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,8715280724
2735,mentioned as the sergeant supervising the inve...,sergeant,"[52, 36, 48, 47, 6, 11, 9, 49, 48, 49, 8, 8, 9...",Exhibit 26 Herman Franklin Deposition Transcri...,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,2,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,9660258395
2742,referred to as the sergeant overseeing the inv...,sergeant,"[14, 36, 14, 38, 6, 69, 11, 39, 8, 9, 49, 8, 3...",Exhibit 26 Herman Franklin Deposition Transcri...,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,4,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,4484307839
2759,mentioned as a sergeant of the public housing ...,sergeant,"[13, 10, 11, 9, 9, 9, 5, 7, 5, 5, 8, 5, 4, 4, ...",Exhibit 20 Supplemental Report on Murder.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,1,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,3862802690
2765,"met with detective leflora young, officer lloy...",sergeant,"[10, 11, 9, 13, 9, 9, 13, 5, 7, 5, 8, 5, 4, 4,...",Exhibit 20 Supplemental Report on Murder.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,2,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,2651207499
2782,"unit #1910, supported units on the scene.",sergeant,"[10, 11, 9, 13, 9, 9, 13, 5, 7, 5, 8, 5, 4, 4,...",Exhibit 20 Supplemental Report on Murder.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,2,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,6443722912
2785,met with detective leflora young at 646 north ...,sergeant,"[11, 10, 6, 9, 9, 13, 5, 1, 5, 7, 5, 4, 8, 4, ...",Exhibit 20 Supplemental Report on Murder.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,3,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,5662187321
2796,"met with detective leflora young, officer lloy...",sergeant,"[13, 9, 10, 7, 9, 6, 4, 9, 8, 5, 5, 5, 5, 4, 2...",Exhibit 20 Supplemental Report on Murder.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,4,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,6332547553
2804,sergeant keith joseph assisted detective leflo...,supporting sergeant,"[9, 13, 10, 9, 11, 9, 1, 7, 5, 8, 5, 4, 5, 4, ...",Exhibit 20 Supplemental Report on Murder.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,5,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,8688211501
2807,unit #1910sgt. keith joseph is listed as a sup...,sergeant,"[7, 4, 6, 9, 13, 1, 9, 5, 4, 5, 8, 5, 5, 4, 12...",Exhibit 20 Supplemental Report on Murder.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,6,1,gpt-3.5-turbo-1603-finetuned-300-labels,6484c798,Keith Joseph,keith,joseph,keith,josep,6825800787
2815,sergeant keith joseph met with other officers ...,sergeant,"[13, 9, 10, 9, 9, 6, 1, 5, 5, 4, 5, 5, 8, 4, 1...",Supplemental Report.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,1,1,gpt-3.5-turbo-1603-finetuned-300-labels,af1a425b,Keith Joseph,keith,joseph,keith,josep,8333958164
2829,assisted in canvassing the area of the crime s...,sergeant,"[7, 7, 11, 12, 13, 6, 5, 5, 5, 4, 9, 8, 4, 5, ...",Supplemental Report.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,2,1,gpt-3.5-turbo-1603-finetuned-300-labels,af1a425b,Keith Joseph,keith,joseph,keith,josep,6480115441
2839,met with other officers and detectives at both...,sergeant,"[9, 10, 9, 6, 13, 12, 9, 7, 5, 5, 8, 5, 4, 4, ...",Supplemental Report.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,3,1,gpt-3.5-turbo-1603-finetuned-300-labels,af1a425b,Keith Joseph,keith,joseph,keith,josep,7247699318
2845,"met with detective leflora young, officer lloy...",sergeant,"[6, 11, 10, 1, 5, 1, 2, 9, 4, 9, 7, 9, 4, 8, 1...",Supplemental Report.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,4,1,gpt-3.5-turbo-1603-finetuned-300-labels,af1a425b,Keith Joseph,keith,joseph,keith,josep,1852031844
2852,"assisted detective herman franklin in a case, ...",sergeant,"[10, 10, 2, 6, 5, 10, 1, 4, 13, 5, 5, 4, 8, 5,...",Supplemental Report.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,5,1,gpt-3.5-turbo-1603-finetuned-300-labels,af1a425b,Keith Joseph,keith,joseph,keith,josep,7481223503
2861,met with detective leflora young and other off...,sergeant,"[2, 7, 10, 12, 13, 6, 9, 5, 9, 4, 8, 5, 5, 4, ...",Supplemental Report.json,"Identify each individual in the transcript, by...",input_variables=['question'] template='\n Y...,"input_variables=['docs', 'question'] template=...",500,250,1,...,6,1,gpt-3.5-turbo-1603-finetuned-300-labels,af1a425b,Keith Joseph,keith,joseph,keith,josep,6960858115
4182,mentioned as the sergeant at the time.,sergeant,"[14, 7, 48, 38, 39, 36, 76, 48, 49, 8, 49, 8, ...",Herman Franklin Deposition Transcript 06.07.13...,"Identify each individual in the transcript, by...",NaN,NaN,500,250,1,...,1,1,gpt-3.5-turbo-1603-finetuned-300-labels,37583c1f,Keith Joseph,keith,joseph,keith,josep,3491496868
4193,mentioned as the sergeant who was overseeing t...,sergeant,"[48, 11, 9, 48, 53, 53, 76, 48, 8, 8, 49, 9, 4...",Herman Franklin Deposition Transcript 06.07.13...,"Identify each individual in the transcript, by...",NaN,NaN,500,250,1,...,3,1,gpt-3.5-turbo-1603-finetuned-300-labels,37583c1f,Keith Joseph,keith,joseph,keith,josep,3959942812
4197,"mentioned as the sergeant of the officer, like...",sergeant,"[38, 8, 48, 11, 48, 47, 76, 49, 8, 48, 49, 8, ...",Herman Franklin Deposition Transcript 06.07.13...,"Identify each individual in the transcript, by...",NaN,NaN,500,250,1,...,4,1,gpt-3.5-turbo-1603-finetuned-300-labels,37583c1f,Keith Joseph,keith,joseph,keith,josep,4452316053

In [60]:
dfc = pd.read_csv("../data/personnel.csv")

dfc.loc[:, "officer_name"] = dfc.first_name.str.cat(dfc.last_name, sep=" ").str.title() 

dfc = dfc[["officer_name", "agency"]] 

dfc

             officer_name                 agency
0            Elvin Davis      st-francisville-pd
1           Melissa Matey  new-orleans-harbor-pd
2          Bradley Acklen               caddo-so
3            Bobby Porter           jefferson-so
4        Barrett Stephens          st-bernard-so
...                   ...                    ...
71096  Ebony Adams-Walker         baton-rouge-pd
71097      Kenneth Norris           jefferson-so
71098  Christopher Dooley     wildlife-fisheries
71099       Edward Gay Vi          terrebonne-so
71100      Julie Marshall             slidell-pd

[71101 rows x 2 columns]

In [61]:
def find_perfect_matches(dfa, dfb, dfc):
    merged_df = pd.merge(dfa, dfb, on='officer_name', how='inner')
    merged_df = pd.merge(merged_df, dfc, on='officer_name', how='inner')

    return merged_df

perf_matches = find_perfect_matches(dfa, dfb, dfc)  

perf_matches = perf_matches.drop_duplicates(subset=["officer_name"])

perf_matches

            officer_name                                   agency
0          Justin Crespo                           new-orleans-pd
16           Herman Cade                           new-orleans-pd
72           Byron Adams                           new-orleans-pd
137        Donald Curole                           new-orleans-pd
138        Patrick Jones                             patterson-pd
153           Sam Gebbia                           new-orleans-pd
171       Richard Marino                           new-orleans-pd
181       Martin Venezia                           new-orleans-pd
247          Chris Davis                                ruston-pd
252         Keith Joseph                           new-orleans-pd
271          Lloyd Clark                  east-jefferson-levee-pd
293        Leflora Young                           new-orleans-pd
309       Charles Little                           new-orleans-pd
320         Henry Kirsch                                kenner-pd
332       Craig Rodrigue                           new-orleans-pd
350        James Stewart  bossier-community-college-university-pd
734         Yvonne Farve                           new-orleans-pd
757           Henry Dean                           new-orleans-pd
773        Harry Stovall                           new-orleans-pd
836          Dwight Deal                           new-orleans-pd
848        Anthony Small                           new-orleans-pd
868        Rodney Bailey                           new-orleans-pd
922      Herman Franklin                           new-orleans-pd
1021          John Moran                               sulphur-pd
1039      Marlon Defillo            new-orleans-constables-office
1043         James Eaton                           new-orleans-pd
1053       Audie Jackson                           new-orleans-pd
1075        Kevin Decker                             jefferson-so
1077  Joseph Catalanotto                           new-orleans-pd
1080         John Miller                       wildlife-fisheries
1098      John Gutierrez                            st-bernard-so
1102      David Dimaggio                            st-bernard-so
1106        Rodney Burke                            st-bernard-so
1115      Kenneth Letort                            st-tammany-so
1120       Albert Clavin                            st-bernard-so
1126      Timothy Bayard                           new-orleans-pd
1131     Donald Rodrigue                           new-orleans-pd
1137         Terry Bunch                  east-jefferson-levee-pd
1139    Gregory Hamilton                           new-orleans-pd
1153     Gregory Johnson                          madisonville-pd
1188         Ryan Aucoin                           new-orleans-pd
1232       Desmond Pratt                           new-orleans-pd
1240     Ananie Mitchell                           new-orleans-pd
1255          James Keen                           new-orleans-pd
1276     Melvin Williams                            tangipahoa-so
1352       Barret Morton                           new-orleans-pd
1391       Gary Marchese                           new-orleans-pd
1897        Wayne Rumore                           new-orleans-pd
1928        Larry Pierce                                 caddo-so
1943     Carlton Lawless                           new-orleans-pd
1947        Mark Jackson                       louisiana-state-pd
2047        David Trahan                           new-orleans-pd
2055         Scott Davis                            st-tammany-so
2233       Wesley Morris                           new-orleans-pd
2336         John Thomas                           baton-rouge-pd
2408       Barry Marquez                           new-orleans-pd
2425     Chris Pelleteri                           new-orleans-pd
2426      Tokishiba Lane                           new-orleans-pd
3823       Thomas Smegal                           new-orleans-pd